version: "3"


services:

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000
    environment:
      PYTHONBUFFERED: 1
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "lunch"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/lunch"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
